import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import Legend from '../components/legend'
import Paper from '../components/paper'
import { photoBlock } from '../components/photo'
import Edit from '../components/edit'
import Footer from '../components/footer'
import { projectBlock } from '../components/project.js'

import tinaFormOptions from '../components/tina_form_options'
import {
  useGithubJsonForm,
  useGithubToolbarPlugins
} from 'react-tinacms-github'
import { getGithubPreviewProps, parseJson } from 'next-tinacms-github'
import { GetStaticProps } from 'next'
import { InlineForm, InlineBlocks } from 'react-tinacms-inline'
import { usePreviewSrc, usePlugin, useCMS, useForm } from 'tinacms'

export default function Home({ file }) {
  const data = file.data
  const cms = useCMS()
  const [pageData, form] = useGithubJsonForm(file, tinaFormOptions)
  usePlugin(form)
  useGithubToolbarPlugins()

  return (
    <InlineForm form={form}>
      <Head>
        <title>{pageData.header.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      <div className='container'>
        <div className='row'>
          <div className='order-2 order-md-1 col-12 col-md-8'>
            <Paper data={pageData} edit={<Edit />} />
          </div>
          <div className='order-1 order-md-2 col-12 col-md-4'>
            <InlineBlocks name='photos' blocks={PHOTO_BLOCKS} />
            <Legend />
          </div>
        </div>
        <div className='row projects__row'>
          <h2> Projects </h2>
        </div>
        <div className='row'>
          <div className='projects'>
            <InlineBlocks name='blocks' blocks={PROJECT_BLOCKS} />
          </div>
        </div>
      </div>

      <Footer />
    </InlineForm>
  )
}

const PROJECT_BLOCKS = { project: projectBlock }
const PHOTO_BLOCKS = { photo: photoBlock }

export const getStaticProps = async function ({ preview, previewData }) {
  if (preview) {
    return getGithubPreviewProps({
      ...previewData,
      fileRelativePath: 'content/home.json',
      parse: parseJson
    })
  }
  return {
    props: {
      sourceProvider: null,
      error: null,
      preview: false,
      file: {
        fileRelativePath: 'content/home.json',
        data: (await import('../content/home.json')).default
      }
    }
  }
}
