import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import Paper from '../components/paper'
import Photo from '../components/photo'
import Edit from '../components/edit'

import tinaFormOptions from '../components/tina_form_options'
import { getGithubPreviewProps, parseJson } from 'next-tinacms-github'
import { GetStaticProps } from 'next'
import { InlineForm } from 'react-tinacms-inline'
import { usePreviewSrc, usePlugin, useCMS, useForm } from 'tinacms'
import data from '../content/home.json'

export default function Home() {
  const cms = useCMS()
  const formConfig = {
    id: '../content/home.json',
    initialValues: data,
    onSubmit() {
      cms.alerts.success('Saved!')
    }
  }

  const [pageData, form] = useForm(formConfig)

  return (
    <InlineForm form={form}>
      <div className='container'>
        <Head>
          <title>{pageData.header.title}</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Header />
        <div className='row'>
          <div className='col-12 col-md-7'>
            <Paper {...pageData} />
          </div>
          <div className='col-12 col-md-5'>
            <Photo />
          </div>
        </div>
        <Edit />
      </div>
    </InlineForm>
  )
}

export const getStaticProps = async function ({ preview, previewData }) {
  if (preview) {
    return getGithubPreviewProps({
      ...previewData,
      fileRelativePath: 'content/home.json',
      parse: parseJson
    })
  }
  return {
    props: {
      sourceProvider: null,
      error: null,
      preview: false,
      file: {
        fileRelativePath: 'content/home.json',
        data: (await import('../content/home.json')).default
      }
    }
  }
}
