import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import Paper from '../components/paper'
import Photo from '../components/photo'
import Edit from '../components/edit'
import { getGithubPreviewProps, parseJson } from 'next-tinacms-github'
import { GetStaticProps } from 'next'

export default function Home({ file }) {
  const data = file.data
  return (
    <div className='container'>
      <Head>
        <title>{data.header.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div className='row'>
        <div className='col-12 col-md-7'>
          <Paper />
        </div>
        <div className='col-12 col-md-5'>
          <Photo />
        </div>
      </div>
      <Edit />
    </div>
  )
}

export const getStaticProps = async function ({ preview, previewData }) {
  if (preview) {
    return getGithubPreviewProps({
      ...previewData,
      fileRelativePath: 'content/home.json',
      parse: parseJson
    })
  }
  return {
    props: {
      sourceProvider: null,
      error: null,
      preview: false,
      file: {
        fileRelativePath: 'content/home.json',
        data: (await import('../content/home.json')).default
      }
    }
  }
}
